---
# Monitoring stack
# Deploy: doppler run -- docker compose -f compose.monitoring.yml up -d
# Requires networking + infra stacks to be running first.

networks:
  monitoring-net:
    external: true
  socket-proxy-watchtower-net:
    driver: bridge
    internal: true
  socket-proxy-monitoring-net:
    driver: bridge
    internal: true

services:

  # ---------------------------------------------------------------------------
  # Docker socket proxy — dedicated instance for Watchtower.
  # POST=1 is required: Watchtower must stop, pull, and recreate containers.
  # Isolated on its own internal network so Traefik's proxy stays read-only.
  # ---------------------------------------------------------------------------
  socket-proxy-watchtower:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy-watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      EVENTS: 1
      PING: 1
      VERSION: 1
      CONTAINERS: 1
      IMAGES: 1
      POST: 1       # write access — required for Watchtower to pull and recreate containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-watchtower-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # Watchtower — auto-updates containers and sends Pushover notifications.
  # Connects to Docker via socket proxy (TCP). Postgres and Valkey excluded.
  # Notifications only at warn level (failures, not every successful update).
  # ---------------------------------------------------------------------------
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    environment:
      # Connect to Docker via proxy (no direct docker.sock mount needed)
      DOCKER_HOST: tcp://socket-proxy-watchtower:2375
      DOCKER_API_VERSION: "1.44"
      # Pushover via shoutrrr — token and user key from Doppler
      WATCHTOWER_NOTIFICATION_URL: "pushover://shoutrrr:${WATCHTOWER_PUSHOVER_TOKEN}@${WATCHTOWER_PUSHOVER_USER_KEY}"
      WATCHTOWER_NOTIFICATIONS_LEVEL: warn
      # Remove old images after successful update
      WATCHTOWER_CLEANUP: "true"
      # Run daily at 04:00 (6-field cron: seconds minutes hours day month weekday)
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
    networks:
      - socket-proxy-watchtower-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # Docker socket proxy — read-only, for Dozzle and Beszel agent.
  # Grants only the endpoints each needs: container list, logs, stats.
  # POST=0 ensures no write operations are possible.
  # ---------------------------------------------------------------------------
  socket-proxy-monitoring:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PING: 1
      VERSION: 1
      INFO: 1
      CONTAINERS: 1
      LOGS: 1
      STATS: 1
      EVENTS: 1
      POST: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-monitoring-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # OpenTelemetry Collector — receives OTLP from apps, forwards to SigNoz
  # on homelab via Tailscale. Ports accessible on monitoring-net + Tailscale.
  # ---------------------------------------------------------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    environment:
      SIGNOZ_OTLP_ENDPOINT: ${SIGNOZ_OTLP_ENDPOINT}
    volumes:
      - ./otel/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    networks:
      - monitoring-net
    # Bind to all interfaces so Tailscale IP is reachable for app instrumentation
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  # ---------------------------------------------------------------------------
  # Beszel agent — sends server metrics to Beszel hub on homelab.
  # Connects to hub via Tailscale IP. Key generated in Beszel hub UI.
  # ---------------------------------------------------------------------------
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 64m
    environment:
      KEY: ${BESZEL_AGENT_KEY}
      DOCKER_HOST: tcp://socket-proxy-monitoring:2375
      # Agent listens on :45876 (Beszel default), accessible via Tailscale only
    ports:
      - "45876:45876"
    networks:
      - monitoring-net
      - socket-proxy-monitoring-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # Dozzle — log viewer running in agent mode.
  # Hub on homelab discovers this agent via Tailscale IP.
  # ---------------------------------------------------------------------------
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 64m
    command: agent
    environment:
      DOZZLE_HOSTNAME: vps
      DOCKER_HOST: tcp://socket-proxy-monitoring:2375
    networks:
      - monitoring-net
      - socket-proxy-monitoring-net
    ports:
      - "7007:7007"   # Agent port, accessible via Tailscale only
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }
