---
# Infrastructure stack — Postgres, Valkey
# Deploy: doppler run -- docker compose -f compose.infra.yml up -d
# Restart with care: backup Postgres first (make backup)

networks:
  postgres-net:
    external: true
  valkey-net:
    external: true

volumes:
  postgres-data:
  valkey-data:

services:

  # ---------------------------------------------------------------------------
  # PostgreSQL 18 — primary database. Pinned to major version.
  # Never exposed externally. Update manually (backup first, then pull).
  # ---------------------------------------------------------------------------
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 2g
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Watchtower: excluded from auto-updates — update manually (backup first)
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  # ---------------------------------------------------------------------------
  # Valkey 9 — Redis-compatible cache and queue backend.
  # container_name: redis so apps can connect via redis:6379 unchanged.
  # Pinned to major version. Update manually.
  # ---------------------------------------------------------------------------
  valkey:
    image: valkey/valkey:9
    container_name: redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    command: valkey-server --maxmemory 400mb --maxmemory-policy allkeys-lru --save 60 1
    volumes:
      - valkey-data:/data
    networks:
      - valkey-net
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Watchtower: excluded from auto-updates — update manually
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }
