---
# Networking/proxy stack — cloudflared, Traefik, socket-proxy, RollHook
# Deploy: doppler run -- docker compose -f compose.networking.yml up -d

networks:
  proxy:
    external: true
  socket-proxy-net:
    driver: bridge
    internal: true
  socket-proxy-rollhook-net:
    driver: bridge
    internal: true

volumes:
  rollhook-data:

services:

  # ---------------------------------------------------------------------------
  # Docker socket proxy — restricts Docker API access to read-only operations.
  # Traefik connects here instead of mounting docker.sock directly.
  # ---------------------------------------------------------------------------
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      IMAGES: 1
      INFO: 1
      # Deny write operations
      POST: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # Cloudflare Tunnel — all public ingress flows through here.
  # No ports exposed to the internet; cloudflared makes outbound connections
  # to Cloudflare edge only. Configure public hostnames in Cloudflare dashboard:
  #   *.DOMAIN → https://traefik:443  (TLS verify: disabled — internal cert)
  # ---------------------------------------------------------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 64m
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # Traefik v3 — reverse proxy + HTTPS via Cloudflare DNS-01 wildcard cert.
  # No ports exposed — cloudflared routes traffic to traefik:443 internally.
  # Entrypoints: web (:80, redirect to websecure) + websecure (:443, TLS).
  # ---------------------------------------------------------------------------
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    ports:
      # Bind websecure entrypoint to Tailscale interface only — dashboard access without Cloudflare.
      # Public apps are still routed via cloudflared (no internet exposure here).
      - "${VPS_TAILSCALE_IP}:443:443"
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      # ACME email: passed as env var because traefik.yml doesn't support ${VAR} substitution
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
    networks:
      - proxy
      - socket-proxy-net
    labels:
      # Traefik dashboard — restricted to Tailscale IP range via middleware
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=tailscale-only@file"
      # Request wildcard cert via DNS-01 — Docker Compose substitutes ${DOMAIN} in labels ✓
      - "traefik.http.routers.dashboard.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.dashboard.tls.domains[0].sans=*.${DOMAIN}"
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  # ---------------------------------------------------------------------------
  # Socket proxy for RollHook — write access (POST=1) for rolling deployments.
  # Isolated on socket-proxy-rollhook-net, never shared with Traefik's proxy.
  # ---------------------------------------------------------------------------
  socket-proxy-rollhook:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy-rollhook
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      CONTAINERS: 1
      SERVICES: 1
      IMAGES: 1
      INFO: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-rollhook-net
    logging:
      driver: json-file
      options: { max-size: "5m", max-file: "2" }

  # ---------------------------------------------------------------------------
  # RollHook — zero-downtime rolling deployments via GitHub Actions webhooks.
  # Receives POST /deploy/:app, scales up new container, waits for healthcheck,
  # then removes the old one. Routed publicly via Cloudflare → Traefik.
  #
  # App compose files must be mounted here for docker-rollout to read them.
  # Add one volume per app:  - /home/jkrumm/<app>:/home/jkrumm/<app>:ro
  # ---------------------------------------------------------------------------
  rollhook:
    image: registry.jkrumm.com/rollhook:latest
    container_name: rollhook
    restart: unless-stopped
    depends_on:
      - socket-proxy-rollhook
    security_opt:
      - no-new-privileges:true
    environment:
      ADMIN_TOKEN: ${ROLLHOOK_ADMIN_TOKEN}
      WEBHOOK_TOKEN: ${ROLLHOOK_WEBHOOK_TOKEN}
      ROLLHOOK_CONFIG_PATH: /app/rollhook.config.yaml
      PORT: "7700"
      DOCKER_HOST: tcp://socket-proxy-rollhook:2375
    volumes:
      - ./config/rollhook/rollhook.config.yaml:/app/rollhook.config.yaml:ro
      - rollhook-data:/app/data
      # docker compose plugin — required for rolling deployments (Ubuntu path: /usr/libexec/)
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/local/lib/docker/cli-plugins/docker-compose:ro
    healthcheck:
      test: [CMD, bun, -e, "fetch('http://localhost:7700/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rollhook.rule=Host(`rollhook-vps.${DOMAIN}`)"
      - "traefik.http.routers.rollhook.entrypoints=websecure"
      - "traefik.http.routers.rollhook.tls.certresolver=letsencrypt"
      - "traefik.http.services.rollhook.loadbalancer.server.port=7700"
      - "traefik.http.routers.rollhook.middlewares=rate-limit@file,security-headers@file"
    networks:
      - proxy
      - socket-proxy-rollhook-net
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
